### PR TITLE
change FBSDKCoreKit to 9.1.0

### PR DESCRIPTION
**Pull request by perez-danilo**
Use the version compatible with:
facebook_app_events 0.12.0

### CODE REVIEW

**Comment by saadfarhan124** [comment]
Can you update the s.platform = :ios, '8.0' to 9.0 and create a new pull request? Thanks

**Comment by saadfarhan124** [comment]
Also app events are supported in this plugin too. Is there any reason you aren't using the same plugin for app events? You can also make a feature request. I'd love to work on this more

**Comment by perez-danilo** [comment]
> Also app events are supported in this plugin too. Is there any reason you aren't using the same plugin for app events? You can also make a feature request. I'd love to work on this more

Hi, i changed the version too.
I did not know that this pluguin write og at facebook like this:
facebookAppEvents.logEvent(
                    name: 'button_clicked',
                    parameters: {
                      'button_id': 'the_clickme_button',
                    },
                  );

**Comment by perez-danilo** [comment]
Support the same thing? If yes i can think to change!

**Comment by saadfarhan124** [comment]
> Support the same thing? If yes i can think to change!
> > Also app events are supported in this plugin too. Is there any reason you aren't using the same plugin for app events? You can also make a feature request. I'd love to work on this more
> 
> Hi, i changed the version too.
> I did not know that this pluguin write og at facebook like this:
> facebookAppEvents.logEvent(
> name: 'button_clicked',
> parameters: {
> 'button_id': 'the_clickme_button',
> },
> );

Okay I'll add support for this

**Comment by saadfarhan124** [comment]
> > Also app events are supported in this plugin too. Is there any reason you aren't using the same plugin for app events? You can also make a feature request. I'd love to work on this more
> 
> Hi, i changed the version too.
> I did not know that this pluguin write og at facebook like this:
> facebookAppEvents.logEvent(
> name: 'button_clicked',
> parameters: {
> 'button_id': 'the_clickme_button',
> },
> );


Hey you can now log generic facebook app events using the same plugin 
Code Example 1 : 

`await flutterFacebookSdk.logEvent(`
`  eventName: "fb_mobile_add_payment_info",`
` // optional field`
`  parameters: {`
`   'SUCCESS': "true",`
`   } ,`
`  // optional field`
`   valueToSum: 55`
`   ),`


Code Example 2 :
 
`await flutterFacebookSdk.logEvent(`
  `eventName: "button_clicked",`
 ` parameters: {`
 `   'button_id': 'the_clickme_button',`
  `},`
`)`

Don't forget to update the plugin first to :

`flutter_facebook_sdk: ^0.0.4`

Let me know if you need anything else.
Also don't forget to star the repo on git and like the plugin on pub.dev if its making your life easier :) 
Thanks

**Pull request merged**
