### PR TITLE
change FBSDKCoreKit to 11.0.0

### PR DESCRIPTION
**Pull request by Ciock**
#### Reference Issues/PRs
None

#### What does this implement?
Upgrade FBSDKCoreKit to 11.0.0 to be compatible with:
flutter_facebook_auth 3.4.1

### CODE REVIEW

**Comment by vishwarajanand** [comment]
Is this tested?

**Comment by Ciock** [comment]
What do you mean by test? I don't see any automated tests in the repository.

If you mean if I've tried it firsthand, yes, I use this branch in a released app.

**Comment by knightowlRaising** [comment]
It's not reflecting on Facebook dev console that the new version is updated! Are you sure only that line of code needed to be upgraded nothing else?

**Comment by Ciock** [comment]
No, i'm not sure.

**Comment by jjsebastianfuertes** [comment]
is there a reason this has not been merged yet?

**Comment by cassiosousa** [comment]
@Ciock, Do you know if this PR fix this issue https://github.com/saadfarhan124/flutter_facebook_sdk/issues/9 ?Can you get test?

**Comment by Ciock** [comment]
I don't think it's related to that issue, but i don't remember exactly what error i run into.

Anyway i'm still using my fork with this upgrade, you can try it and see if it fix the issue.
```
flutter_facebook_sdk:
    git:
      url: https://github.com/Ciock/flutter_facebook_sdk
      ref: master
```

**Pull request merged**
